version: "3.7"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gork
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
  worker:
    build:
      context: ./..
      dockerfile: ./example/worker/Dockerfile
    stop_signal: SIGTERM
    restart: on-failure
    environment:
      - POSTGRES_URI=postgres://root:root@postgres:5432/gork?sslmode=disable
    depends_on:
      - postgres
  client:
    build:
      context: ./..
      dockerfile: ./example/client/Dockerfile
    stop_signal: SIGTERM
    restart: on-failure
    environment:
      - POSTGRES_URI=postgres://root:root@postgres:5432/gork?sslmode=disable
    depends_on:
      - postgres
